-- 코드를 작성해주세요
SELECT DISTINCT D.ID AS ID, D.EMAIL AS EMAIL, D.FIRST_NAME AS FIRST_NAME, D.LAST_NAME AS LAST_NAME
FROM DEVELOPERS D INNER JOIN SKILLCODES S ON S.CODE & D.SKILL_CODE != 0
WHERE S.NAME = 'Python' OR S.NAME = 'C#'
ORDER BY ID